# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_motion_ver4.ui'
#
# Created: Sun Sep 06 22:53:53 2020
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1221, 704)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupRec = QtGui.QGroupBox(self.centralwidget)
        self.groupRec.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupRec.sizePolicy().hasHeightForWidth())
        self.groupRec.setSizePolicy(sizePolicy)
        self.groupRec.setMaximumSize(QtCore.QSize(400, 200))
        self.groupRec.setObjectName(_fromUtf8("groupRec"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupRec)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ledRecording = QtGui.QLabel(self.groupRec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledRecording.sizePolicy().hasHeightForWidth())
        self.ledRecording.setSizePolicy(sizePolicy)
        self.ledRecording.setMinimumSize(QtCore.QSize(10, 10))
        self.ledRecording.setText(_fromUtf8(""))
        self.ledRecording.setObjectName(_fromUtf8("ledRecording"))
        self.horizontalLayout_2.addWidget(self.ledRecording)
        self.buttonRec = QtGui.QPushButton(self.groupRec)
        self.buttonRec.setEnabled(False)
        self.buttonRec.setObjectName(_fromUtf8("buttonRec"))
        self.horizontalLayout_2.addWidget(self.buttonRec)
        self.label_4 = QtGui.QLabel(self.groupRec)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_Filename = QtGui.QLineEdit(self.groupRec)
        self.lineEdit_Filename.setMaxLength(20)
        self.lineEdit_Filename.setObjectName(_fromUtf8("lineEdit_Filename"))
        self.horizontalLayout_2.addWidget(self.lineEdit_Filename)
        self.buttonSetFilename = QtGui.QPushButton(self.groupRec)
        self.buttonSetFilename.setObjectName(_fromUtf8("buttonSetFilename"))
        self.horizontalLayout_2.addWidget(self.buttonSetFilename)
        self.gridLayout_2.addWidget(self.groupRec, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonOpenfile = QtGui.QPushButton(self.groupBox)
        self.buttonOpenfile.setObjectName(_fromUtf8("buttonOpenfile"))
        self.horizontalLayout.addWidget(self.buttonOpenfile)
        self.gridLayout_2.addWidget(self.groupBox, 0, 3, 1, 1)
        self.groupCon = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupCon.sizePolicy().hasHeightForWidth())
        self.groupCon.setSizePolicy(sizePolicy)
        self.groupCon.setMaximumSize(QtCore.QSize(160, 140))
        self.groupCon.setObjectName(_fromUtf8("groupCon"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupCon)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ledConnection = QtGui.QLabel(self.groupCon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledConnection.sizePolicy().hasHeightForWidth())
        self.ledConnection.setSizePolicy(sizePolicy)
        self.ledConnection.setMinimumSize(QtCore.QSize(10, 10))
        self.ledConnection.setText(_fromUtf8(""))
        self.ledConnection.setObjectName(_fromUtf8("ledConnection"))
        self.horizontalLayout_3.addWidget(self.ledConnection)
        self.buttonConnect = QtGui.QPushButton(self.groupCon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConnect.sizePolicy().hasHeightForWidth())
        self.buttonConnect.setSizePolicy(sizePolicy)
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.horizontalLayout_3.addWidget(self.buttonConnect)
        self.gridLayout_2.addWidget(self.groupCon, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(800, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_angle = QtGui.QWidget()
        self.tab_angle.setObjectName(_fromUtf8("tab_angle"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_angle)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_angle)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.rollAngle = QtGui.QLineEdit(self.groupBox_2)
        self.rollAngle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rollAngle.setMaxLength(3)
        self.rollAngle.setObjectName(_fromUtf8("rollAngle"))
        self.horizontalLayout_4.addWidget(self.rollAngle)
        self.buttonCorrect = QtGui.QPushButton(self.groupBox_2)
        self.buttonCorrect.setObjectName(_fromUtf8("buttonCorrect"))
        self.horizontalLayout_4.addWidget(self.buttonCorrect)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 3, 1, 1)
        self.groupFilter = QtGui.QGroupBox(self.tab_angle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupFilter.sizePolicy().hasHeightForWidth())
        self.groupFilter.setSizePolicy(sizePolicy)
        self.groupFilter.setObjectName(_fromUtf8("groupFilter"))
        self.gridLayout = QtGui.QGridLayout(self.groupFilter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboFilterType = QtGui.QComboBox(self.groupFilter)
        self.comboFilterType.setObjectName(_fromUtf8("comboFilterType"))
        self.comboFilterType.addItem(_fromUtf8(""))
        self.comboFilterType.addItem(_fromUtf8(""))
        self.comboFilterType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboFilterType, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupFilter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupFilter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.paramOrder = QtGui.QLineEdit(self.groupFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramOrder.sizePolicy().hasHeightForWidth())
        self.paramOrder.setSizePolicy(sizePolicy)
        self.paramOrder.setMinimumSize(QtCore.QSize(20, 20))
        self.paramOrder.setMaximumSize(QtCore.QSize(40, 16777215))
        self.paramOrder.setMaxLength(2)
        self.paramOrder.setObjectName(_fromUtf8("paramOrder"))
        self.gridLayout.addWidget(self.paramOrder, 0, 4, 1, 1)
        self.buttonApplyFilter = QtGui.QPushButton(self.groupFilter)
        self.buttonApplyFilter.setObjectName(_fromUtf8("buttonApplyFilter"))
        self.gridLayout.addWidget(self.buttonApplyFilter, 0, 7, 1, 1)
        self.paramCutoff = QtGui.QLineEdit(self.groupFilter)
        self.paramCutoff.setMaximumSize(QtCore.QSize(40, 16777215))
        self.paramCutoff.setMaxLength(3)
        self.paramCutoff.setObjectName(_fromUtf8("paramCutoff"))
        self.gridLayout.addWidget(self.paramCutoff, 0, 6, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupFilter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.buttonExport = QtGui.QPushButton(self.groupFilter)
        self.buttonExport.setObjectName(_fromUtf8("buttonExport"))
        self.gridLayout.addWidget(self.buttonExport, 0, 8, 1, 1)
        self.gridLayout_3.addWidget(self.groupFilter, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(292, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 7, 1, 1)
        self.angleplot = PlotWidget(self.tab_angle)
        self.angleplot.setObjectName(_fromUtf8("angleplot"))
        self.gridLayout_3.addWidget(self.angleplot, 0, 0, 1, 8)
        self.degLabel = QtGui.QLabel(self.tab_angle)
        self.degLabel.setMaximumSize(QtCore.QSize(250, 200))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.degLabel.setFont(font)
        self.degLabel.setAutoFillBackground(False)
        self.degLabel.setObjectName(_fromUtf8("degLabel"))
        self.gridLayout_3.addWidget(self.degLabel, 1, 5, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(292, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 4, 1, 1)
        self.degLabel_2 = QtGui.QLabel(self.tab_angle)
        self.degLabel_2.setMaximumSize(QtCore.QSize(250, 200))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.degLabel_2.setFont(font)
        self.degLabel_2.setAutoFillBackground(False)
        self.degLabel_2.setObjectName(_fromUtf8("degLabel_2"))
        self.gridLayout_3.addWidget(self.degLabel_2, 1, 6, 1, 1)
        self.tabWidget.addTab(self.tab_angle, _fromUtf8(""))
        self.tab_init = QtGui.QWidget()
        self.tab_init.setObjectName(_fromUtf8("tab_init"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_init)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.accplotx = PlotWidget(self.tab_init)
        self.accplotx.setObjectName(_fromUtf8("accplotx"))
        self.verticalLayout_2.addWidget(self.accplotx)
        self.accploty = PlotWidget(self.tab_init)
        self.accploty.setObjectName(_fromUtf8("accploty"))
        self.verticalLayout_2.addWidget(self.accploty)
        self.accplotz = PlotWidget(self.tab_init)
        self.accplotz.setObjectName(_fromUtf8("accplotz"))
        self.verticalLayout_2.addWidget(self.accplotz)
        self.tabWidget.addTab(self.tab_init, _fromUtf8(""))
        self.tab_levels = QtGui.QWidget()
        self.tab_levels.setObjectName(_fromUtf8("tab_levels"))
        self.head_Xn = QtGui.QProgressBar(self.tab_levels)
        self.head_Xn.setGeometry(QtCore.QRect(482, 111, 201, 31))
        self.head_Xn.setProperty("value", 0)
        self.head_Xn.setTextVisible(False)
        self.head_Xn.setInvertedAppearance(True)
        self.head_Xn.setObjectName(_fromUtf8("head_Xn"))
        self.torso_Xn = QtGui.QProgressBar(self.tab_levels)
        self.torso_Xn.setGeometry(QtCore.QRect(482, 330, 201, 31))
        self.torso_Xn.setProperty("value", 0)
        self.torso_Xn.setTextVisible(False)
        self.torso_Xn.setInvertedAppearance(True)
        self.torso_Xn.setObjectName(_fromUtf8("torso_Xn"))
        self.head_Xp = QtGui.QProgressBar(self.tab_levels)
        self.head_Xp.setGeometry(QtCore.QRect(682, 111, 201, 31))
        self.head_Xp.setProperty("value", 0)
        self.head_Xp.setTextVisible(False)
        self.head_Xp.setInvertedAppearance(False)
        self.head_Xp.setObjectName(_fromUtf8("head_Xp"))
        self.torso_Xp = QtGui.QProgressBar(self.tab_levels)
        self.torso_Xp.setGeometry(QtCore.QRect(682, 330, 201, 31))
        self.torso_Xp.setProperty("value", 0)
        self.torso_Xp.setTextVisible(False)
        self.torso_Xp.setInvertedAppearance(False)
        self.torso_Xp.setObjectName(_fromUtf8("torso_Xp"))
        self.label_6 = QtGui.QLabel(self.tab_levels)
        self.label_6.setGeometry(QtCore.QRect(372, 110, 91, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_levels)
        self.label_7.setGeometry(QtCore.QRect(362, 320, 111, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.level_image = QtGui.QLabel(self.tab_levels)
        self.level_image.setGeometry(QtCore.QRect(100, 50, 228, 374))
        self.level_image.setText(_fromUtf8(""))
        self.level_image.setObjectName(_fromUtf8("level_image"))
        self.line = QtGui.QFrame(self.tab_levels)
        self.line.setGeometry(QtCore.QRect(673, 146, 20, 179))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_8 = QtGui.QLabel(self.tab_levels)
        self.label_8.setGeometry(QtCore.QRect(660, 60, 46, 41))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_levels)
        self.label_9.setGeometry(QtCore.QRect(850, 60, 71, 41))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_levels)
        self.label_10.setGeometry(QtCore.QRect(460, 60, 46, 41))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame_image = QtGui.QLabel(self.tab_levels)
        self.frame_image.setGeometry(QtCore.QRect(890, 190, 289, 228))
        self.frame_image.setText(_fromUtf8(""))
        self.frame_image.setObjectName(_fromUtf8("frame_image"))
        self.tabWidget.addTab(self.tab_levels, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 3, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyTHang: Head-Torso Angle Measurement System", None))
        self.groupRec.setTitle(_translate("MainWindow", "Recording", None))
        self.buttonRec.setText(_translate("MainWindow", "Start Recording", None))
        self.label_4.setText(_translate("MainWindow", "File name :", None))
        self.buttonSetFilename.setText(_translate("MainWindow", "Update name", None))
        self.groupBox.setTitle(_translate("MainWindow", "Browser", None))
        self.buttonOpenfile.setText(_translate("MainWindow", "Open Log File", None))
        self.groupCon.setTitle(_translate("MainWindow", "Device", None))
        self.buttonConnect.setText(_translate("MainWindow", "Connect", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Correction", None))
        self.label_5.setText(_translate("MainWindow", "Roll Angle:", None))
        self.buttonCorrect.setText(_translate("MainWindow", "Set", None))
        self.groupFilter.setTitle(_translate("MainWindow", "Filtering", None))
        self.comboFilterType.setItemText(0, _translate("MainWindow", "Low Pass", None))
        self.comboFilterType.setItemText(1, _translate("MainWindow", "High Pass", None))
        self.comboFilterType.setItemText(2, _translate("MainWindow", "Band Pass", None))
        self.label.setText(_translate("MainWindow", "Type :", None))
        self.label_2.setText(_translate("MainWindow", "Order :", None))
        self.buttonApplyFilter.setText(_translate("MainWindow", "Apply Filter", None))
        self.label_3.setText(_translate("MainWindow", "Cut-off (Hz):", None))
        self.buttonExport.setText(_translate("MainWindow", "Export Filtered", None))
        self.degLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">0</span></p></body></html>", None))
        self.degLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000; vertical-align:super;\">o</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_angle), _translate("MainWindow", "Estimated Angle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_init), _translate("MainWindow", "Raw Data", None))
        self.head_Xn.setFormat(_translate("MainWindow", "%p%", None))
        self.torso_Xn.setFormat(_translate("MainWindow", "%p%", None))
        self.head_Xp.setFormat(_translate("MainWindow", "%p%", None))
        self.torso_Xp.setFormat(_translate("MainWindow", "%p%", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">HEAD</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">TORSO</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">0</span></p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">0.1</span></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">0.1</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_levels), _translate("MainWindow", "Sensor Alignment", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

